import io
import logging
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from typing import Optional, List

logger = logging.getLogger(__name__)

# OMR Design constants
BUBBLE_RADIUS = 2.2 * mm
CHOICE_SPACING = 7.5 * mm
ROW_HEIGHT = 8.5 * mm
COLUMN_SPACING = 45 * mm
CHOICE_LABELS = ["A", "B", "C", "D", "E"]
BRAND_GREEN = colors.HexColor("#059669")

def generate_omr_sheet(
    title: str = "OMR Answer Sheet",
    school_name: str = "",
    question_count: int = 50,
    choices_per_q: int = 4,
    show_timing_marks: bool = True
) -> bytes:
    """
    Generate a printable OMR answer sheet PDF.
    """
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4

    # 1. Background / Border
    c.setStrokeColor(colors.black)
    c.setLineWidth(0.5)
    # c.rect(10*mm, 10*mm, width - 20*mm, height - 20*mm)

    # 2. Timing Marks (Corner Squares)
    if show_timing_marks:
        c.setFillColor(colors.black)
        mark_size = 5 * mm
        # Bottom-left, Bottom-right, Top-left, Top-right
        c.rect(10*mm, 10*mm, mark_size, mark_size, fill=1)
        c.rect(width - 15*mm, 10*mm, mark_size, mark_size, fill=1)
        c.rect(10*mm, height - 15*mm, mark_size, mark_size, fill=1)
        c.rect(width - 15*mm, height - 15*mm, mark_size, mark_size, fill=1)

    # 3. Header
    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(width/2, height - 25*mm, title.upper())
    
    if school_name:
        c.setFont("Helvetica", 12)
        c.drawCentredString(width/2, height - 32*mm, school_name)

    # Student Info Fields
    c.setFont("Helvetica", 10)
    y_info = height - 48*mm
    c.drawString(20*mm, y_info, "Student Name: ________________________________")
    c.drawString(120*mm, y_info, "Roll No: ____________")
    c.drawString(20*mm, y_info - 8*mm, "Class: ______________")
    c.drawString(70*mm, y_info - 8*mm, "Date: _______________")
    c.drawString(120*mm, y_info - 8*mm, "Invigilator Sign: ____________")

    c.setStrokeColor(colors.lightgrey)
    c.line(20*mm, y_info - 14*mm, width - 20*mm, y_info - 14*mm)

    # 4. Bubble Grid
    c.setFont("Helvetica-Bold", 8)
    c.setStrokeColor(colors.black)
    c.setLineWidth(0.8)

    # Column configuration
    # 20 questions -> 1 column
    # 50 questions -> 2 columns (25 each)
    # 100 questions -> 4 columns (25 each) or similar
    questions_per_col = 25
    num_cols = (question_count + questions_per_col - 1) // questions_per_col
    
    start_x = 25 * mm
    start_y = height - 75 * mm
    
    for q_idx in range(question_count):
        col = q_idx // questions_per_col
        row = q_idx % questions_per_col
        
        x = start_x + (col * COLUMN_SPACING)
        y = start_y - (row * ROW_HEIGHT)
        
        # Question Number
        c.setFillColor(colors.black)
        c.drawRightString(x - 4*mm, y - 1*mm, f"{q_idx + 1}")
        
        # Choice Bubbles
        for ch_idx in range(choices_per_q):
            bx = x + (ch_idx * CHOICE_SPACING)
            by = y
            
            c.circle(bx, by, BUBBLE_RADIUS, stroke=1, fill=0)
            
            # Label inside/above bubble?
            c.setFont("Helvetica", 6)
            c.drawCentredString(bx, by - 1*mm, CHOICE_LABELS[ch_idx])
            c.setFont("Helvetica-Bold", 8)

    # 5. Footer / Instructions
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(colors.grey)
    instr_y = 25*mm
    c.drawString(20*mm, instr_y, "Instructions: Use blue/black ballpoint pen only. Fill the bubble completely.")
    c.drawRightString(width - 20*mm, instr_y, "Generated by Markix OMR")

    c.showPage()
    c.save()
    return buf.getvalue()
